DROP TABLE IF EXISTS scheduled_notification CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS couple CASCADE;

CREATE TABLE couple
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    shared_message VARCHAR(24),
    status         VARCHAR(30),
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "user"
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email            VARCHAR(255),
    birth_date       TIMESTAMP,
    is_deleted       BOOLEAN               DEFAULT FALSE,
    platform         VARCHAR(50)  NOT NULL,
    platform_user_id VARCHAR(255) NOT NULL,
    nickname         VARCHAR(8),
    gender           VARCHAR(50),
    user_status      VARCHAR(50)  NOT NULL DEFAULT 'NEW',
    couple_id        BIGINT,
    created_at       TIMESTAMP             DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP             DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_unique_idx_platform_user_id_when_not_deleted UNIQUE (platform_user_id)
);

CREATE TABLE scheduled_notification
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_user_id    BIGINT       NOT NULL,
    notification_type VARCHAR(50)  NOT NULL,
    notify_at         TIMESTAMP    NOT NULL,
    title             VARCHAR(255) NOT NULL,
    body              VARCHAR(255) NOT NULL,
    image             VARCHAR(255),
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_target_user FOREIGN KEY (target_user_id) REFERENCES "user" (id)
);


