spring:
  config:
    import: optional:file:../.env[.properties]
  datasource:
    hikari:
      maximum-pool-size: ${DB_MAX_CONNECTION}
      connection-test-query: "SELECT 1"
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        show_sql: true
        format_sql: true
        highlight_sql: true
        jdbc:
          batch_size: 10
