spring:
  config:
    activate:
      on-profile: test
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/caramel
    username: caramel
    password: ''
    hikari:
      maximum-pool-size: 12
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: true
        globally_quoted_identifiers: true
        order_updates: true
        jdbc:
          batch_size: 20
  cloud:
    openfeign:
      okhttp:
        enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      password: ""
  test:
    database:
      replace: none
