spring:
  config:
    activate:
      on-profile: test
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/caramel
    username: caramel
    password: 'abcdefghijklnmopqrstuvwxyz'
    hikari:
      maximum-pool-size: 12
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: true
        globally_quoted_identifiers: true
        order_updates: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
  cloud:
    openfeign:
      okhttp:
        enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      password: ""
  test:
    database:
      replace: none

jwt:
  secret-key-str: "a-very-long-and-secure-secret-key-for-testing-purpose-only-at-least-256-bits"
  access-expiration-sec: 3600
  refresh-expiration-sec: 604800
  issuer: Caramel
