name: Caramel CI

on:
  # push:
  #   branches: [ "develop" ]
  pull_request:
    types: [ opened, ready_for_review ]

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      # - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle Test
        run: ./gradlew --info test

      # NOTE: The Gradle Wrapper is the default and recommended way to run Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
      # If your project does not have the Gradle Wrapper configured, you can use the following configuration to run Gradle with a specified version.
      #
      # - name: Setup Gradle
      #   uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      #   with:
      #     gradle-version: '8.9'
      #
      # - name: Build with Gradle 8.9
      #   run: gradle build

      - name: Jacoco Report
        uses: Madrapps/jacoco-report@v1.7.2
        with:
          # Comma separated paths of the generated jacoco xml files (supports wildcard glob pattern)
          paths: ${{ github.workspace }}/build/jacocoXml/test/jacocoTestRepost.xml
          # Github personal token to add comments to Pull Request
          token: ${{ secrets.GIT_TOKEN }}
          # The minimum code coverage that is required to pass for overall project
          min-coverage-overall: 40 # optional, default is 80
          # The minimum code coverage that is required to pass for changed files
          min-coverage-changed-files: 40 # optional, default is 80
          # Optional title for the Pull Request comment
          title: Caramel Code Coverage # optional
          # Update the coverage report comment instead of creating new ones. Requires title to works properly.
          update-comment: true # optional, default is false

            # Specifies where to add the comment, whether as a PR comment, workflow summary, or both.
            # comment-type: # optional, default is pr_comment
            # The PR number to add the comment to. If not provided, the action will try to get it from the environment.
            # pr-number: # optional
            # Comment won't be added if there is no coverage information present for the files changed
            # skip-if-no-changes: # optional, default is false
            # Github emoji to use for pass status shown when coverage greater than min coverage (should be a Github supported emoji)
            # pass-emoji: # optional, default is :green_apple:
            # Github emoji to use for fail status shown when coverage lesser than min coverage (should be a Github supported emoji)
            # fail-emoji: # optional, default is :x:
            # When there is an error do not fail the action, but log a warning
            # continue-on-error: # optional, default is true
            # Run the action in debug mode and get debug logs printed in console
            # debug-mode: # optional, default is false


      - name: Upload Jacoco HTML report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html-report
          path: ${{ github.workspace }}/build/jacocoReport/test/html